### ISSUE TITLE
Segmentation fault in ReadArm

### ISSUE THREAD

**Issue by buglloc** [DimaSmirnov/Archlinux-downgrader#12]
Try to use `downgrader` but it fails with `SIGSEGV`:
```plain
 $ gdb --args ./downgrader php
[...]
(gdb) r
Starting program: /home/buglloc/work/projects/Archlinux-downgrader/downgrader php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
 Downgrade package: php  
[New Thread 0x7ffff364e700 (LWP 2643)]
[Thread 0x7ffff364e700 (LWP 2643) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6d8cbda in __strcmp_sse2_unaligned () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6d8cbda in __strcmp_sse2_unaligned () from /usr/lib/libc.so.6
#1  0x00000000004024cd in ReadArm (package=0x7fffffffeb80 "php") at Actions.h:244
#2  0x0000000000401811 in IsPackageAvailable (package=0x7fffffffeb80 "php") at Actions.h:46
#3  0x0000000000401870 in CheckDowngradePossibility (package=0x7fffffffeb80 "php") at Actions.h:56
#4  0x0000000000402a79 in main (argc=2, argv=0x7fffffffe8a8) at main.c:61
(gdb) f 1
#1  0x00000000004024cd in ReadArm (package=0x7fffffffeb80 "php") at Actions.h:244
244			if (strcmp(str,"multilib-testing") && strcmp(str,"testing") ) { // Exclude packages from `testing`
(gdb) printf "i: %d, l: %d, pkgs_in_arm: %d, str: %x\n", i, l, pkgs_in_arm, str
i: 30, l: 57, pkgs_in_arm: 30, str: 0
```

Seems problem in `ReadArm`:
```c
int l=0, i=1;
while (i<=pkgs_in_arm) { // Get info about packages in ARM
	strcpy(full,arm_pkgs[l].full_path);
	str = strtok(full, "|");
	if (strcmp(str,"multilib-testing") && strcmp(str,"testing") ) { // Exclude packages from `testing`
		[...]
		i++;
	}
	l++;
}
```

**Comment by DimaSmirnov** [comment]
Hi.
Looks like I fix this problem some days ago.
Please update(reinstall) downgrader from AUR, or build it direct from github.
Problem solved ?
